config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "homes/about"=>"homes#about"
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books ,dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
def index
  @user=User.find(current_user.id)
  @book=Book.new
  @books=Book.all
end

def create
 @book=Book.new(book_params)
 @user=User.find(current_user.id)
 @books=Book.all
 @book.user_id=current_user.id
 @book.save
 redirect_to book_path(@book.id)
end

def show
    @book=Book.new
    @book=Book.find(params[:id])
    @user=User.find(@book.user_id)
end

def edit
  @book=Book.find(params[:id])
end

def update
  @book=Book.find(params[:id])
  @book.update(book_params)
  redirect_to book_path(@book.id)
end

def destroy
  @book=Book.find(params[:id])
  @book.destroy
  redirect_to books_path
end

private
  def book_params
    params.permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book=Book.new
    @users=User.all
    @user=current_user

  end

  def create
  end

  def show
    @user=User.find(params[:id])
    @book=Book.new
    @books=@user.books

  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
  end

  private

 def user_params
  params.require(:user).permit(:name,:introduction,:profile_image)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<div ckass="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model:@book, url:book_path(@book.id) ,local:true do |f| %>
      <div class="form-group">
        <lavel for="title">Title</lavel>
        <%= f.text_field :title,class:"form-control book_title" %>
      </div>
      <div class="form-group">
        <lavel for="body">Opinion</lavel>
        <%= f.text_area :body,class:"form-control book_body" %>
      </div>
      <div class="actions">
        <%= f.submit"Update Book",class:"btn btn-success"%>
      </div>
      <% end %>
      <%= link_to "Show",book_path(@book.id)%>
      |
      <%= link_to "Back",book_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, size:"100x100",format:"jpeg",fallback:"no_image.jpg"%>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th>
              <%= @user.name %>
            </th>
          </tr>
          <tr>
            <th>introuction</th>
            <th>
              <%= @user.introduction %>
            </th>
          </tr>
        </tbody>
      </table>
      <div class="row">
      <%= link_to "",edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog"%>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book,url:books_path ,local:true do |f| %>
      <div class="form-group">
        <label for="title">Title</label>
        <%= f.text_field :title ,class:"form-control book_title" %>
      </div>
      <div class="form-group">
        <labal for="body">Opiniton</labal>
        <%= f.text_area :body,class:"form-control book_body" %>
      </div>
      <div class="action">
        <%= f.submit"Create Book",class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opiniton</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image,format: "jpeg",fallback: "no_image.jpg",size: "40x40"%>
              <% end %>
            </td>
            <td>
              <%= link_to book.title,book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render '/users/list',user: @user, new: @new %>

     <div class="col-md-8 offset-md-1">
      <h2>Book details</h2>
      <table class="table  table-striped">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user_id) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill,40,40,fallback:"no_image.jpg",size: "40x40"%><br>
              <%= link_to @book.user.name,user_path(@book.user_id) %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title,book_path(@book.id) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <% if @book.user==current_user %>
            <td>
              <%= link_to "Edit",edit_book_path(@book.id),class:"btn btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy",book_path(@book.id),method: :delete,"data-confirm" =>"Are you sure?",class:"btn btn-danger" %>
            </td>
            <% end %>
          </tr>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange your opinions, inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <% if user_signed_in? %>
          <%= link_to "Log in",current_user,class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
          <% else %>
          <%= link_to "Log in",new_user_session_path,class:"btn btn-info btn-sm btn-block mb-3 sign_in"%>
          <% end %>
        </div>
        <div class="row">
         <% if user_signed_in? %>
         <%= link_to "Sign Up",current_user,class:"btn btn-success btn-sm btn-block sign_up"%>
         <% else %>
         <%= link_to "Sign Up",new_user_registration_path,class:"btn btn-success btn-sm btn-block sign_up"%>
         <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
             <% if user_signed_in? %>
             <li>
               <%= link_to "Home",user_path(current_user.id),class:"fas fa-home nav-link text-light"%>
             </li>
             <li>
               <%= link_to "Users",users_path,class:"fas fa-users nav-link text-light"%>
             </li>
             <li>
               <%= link_to "Books",books_path,class:"fas fa-book-open nav-link text-light"%>
             </li>
             <li>
               <%= link_to "logout",destroy_user_session_path,method: :delete,class:"fas fa-sign-out-alt nav-link text-light"%>
             </li>
             <% else %>
             <li>
               <%= link_to "Home",root_path,class:"fas fa-home nav-link text-light"%>
             </li>
             <li>
               <%= link_to "About",homes_about_path,class:"fas fa-link nav-link text-light"%>
             </li>
             <li>
               <%= link_to "sign up",new_user_registration_path,class:"fas fa-user-plus nav-link text-light"%>
             </li>
             <li>
               <%= link_to "login",new_user_session_path,class:"fas fa-sign-in-alt nav-link text-light"%>
             </li>
             <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
        <div class="container mt-5">
            <div class="row">
                <div class="mx-auto">
                    <p>CopyRight Infratop.inc</p>
                </div>
            </div>
        </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, size: "100x100",format: "jpeg",fallback: "no_image.jpg"%>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th>
              <%= user.name %>
            </th>
          </tr>
          <tr>
            <th>introuction</th>
            <th>
              <%= user.introduction %>
            </th>
          </tr>
        </tbody>
      </table>
      <div class="row">
      <%= link_to "",edit_user_path(user),class:"btn btn-outline-secondary btn-block fas fa-user-cog"%>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model:new,url:books_path ,local:true do |f| %>
      <div class="form-group">
        <label for="title">Title</label>
        <%= f.text_field :title ,class:"form-control book_title" %>
      </div>
      <div class="form-group">
        <labal for="body">Opiniton</labal>
        <%= f.text_area :body,class:"form-control book_body" %>
      </div>
      <div class="action">
        <%= f.submit"Create Book",class:"btn btn-success" %>
      </div>
      <% end %>
    </div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info </h2>
   <%= form_with model:@user ,local:true do |f| %>
   <div class="form-group">
     <label for="user_name">Name</label>
     <%= f.text_field :name,class:"form-control book_title" %>
   </div>
   <div class="form-group">
     <label for="user_image">Image</label>
     <%= f.attachment_field :profile_image,placeholder:"プロフィール画像" %>
   </div>
   <div class="form-group">
     <label for="body">Introduction</label>
     <%= f.text_area :introduction,class:"form-control book_body" %>
   </div>
   <div class="actions">
     <%= f.submit "Update User",class:"btn btn-success" %>
   </div>
   <% end %>
  </div>
  </div>
</div>

app/views/users/index.html.erb
 <p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, size:"100x100",format: "jpeg",fallback:"no_image.jpg"%>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th>
              <%= @user.name %>
            </th>
          </tr>
          <tr>
            <th>introuction</th>
            <th>
              <%= @user.introduction %>
            </th>
          </tr>
        </tbody>
      </table>
      <div class="row">
      <%= link_to "",edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog"%>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book,url:books_path ,local:true do |f| %>
      <div class="form-group">
        <label for="title">Title</label>
        <%= f.text_field :title ,class:"form-control book_title" %>
      </div>
      <div class="form-group">
        <labal for="body">Opiniton</labal>
        <%= f.text_area :body,class:"form-control book_body" %>
      </div>
      <div class="action">
        <%= f.submit"Create Book",class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>

              <%= attachment_image_tag user, :profile_image,fallback: "no_image.jpg",size: "40x40"%>

            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
             <%= link_to "Show" ,user_path(user.id) %>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render '/users/list',user: @user, new: @new %>

     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover  table-inverse">
        <thred>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opiniton</th>
           <th colspan="3"></th>
          </tr>
        </thred>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image,fallback:"no_image.jpg", size: "40x40"%>
              <% end %>
            </td>
            <td>
              <%= link_to book.title,book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>